FROM php:8.3.0-fpm-alpine3.18

COPY certificates/adp_rootca.crt /usr/local/share/ca-certificates/adp_rootca.crt
RUN update-ca-certificates --fresh

RUN apk update && apk upgrade

RUN apk add \
    git \
    libzip-dev \
    postgresql-dev \
    icu-dev \
    zlib-dev \
    freetype-dev \
    libpng-dev \
    libjpeg-turbo-dev \
    jpeg-dev

RUN docker-php-ext-configure \
    gd \
    --with-freetype \
    --with-jpeg

RUN docker-php-ext-install \
    intl \
    pdo_pgsql \
    gd \
    zip \
    opcache

COPY docker-phpfpm/zz-pm-overrides.conf /usr/local/etc/php-fpm.d/
COPY docker-phpfpm/php-ini-overrides.ini /usr/local/etc/php/conf.d/

# Install dependencies and xdebug in one layer
RUN apk --no-cache add pcre-dev ${PHPIZE_DEPS} \
  && apk add --update linux-headers \
  && pecl install xdebug-3.3.0 && docker-php-ext-enable xdebug \
  && apk del pcre-dev ${PHPIZE_DEPS}

# Copy the Xdebug configuration file
COPY ./docker-phpfpm/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php --install-dir=/usr/local/bin --filename=composer
RUN php -r "unlink('composer-setup.php');"

COPY --chown=www-data . /var/www

RUN mkdir -p /var/www/var/cache

WORKDIR /var/www

RUN chown -R www-data: /var/www

USER www-data

RUN composer install --prefer-dist --no-progress --no-suggest --no-scripts

RUN vendor/bin/grumphp run -n

CMD ["php-fpm"]
