version: "3"
services:
  mm-api_phpfpm:
    build:
      context: .
      dockerfile: Dockerfile_phpfpm_local
    image: ${REGISTRY:-127.0.0.1:5001}/${REPOSITORY:-salmagundi/mm-api}:${VERSION:-latest}
  mm-api_nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    depends_on:
      - mm-api_phpfpm
    image: ${REGISTRY:-127.0.0.1:5001}/${REPOSITORY:-salmagundi/mm-api-nginx}:${VERSION:-latest}
