FROM nginx:stable-alpine

COPY certificates/adp_rootca.crt /usr/local/share/ca-certificates/adp_rootca.crt
RUN update-ca-certificates --fresh

RUN apk update && apk upgrade

COPY docker-nginx/default.template /tmp/default.template
COPY --chown=nginx ./public /var/www/public

WORKDIR /var/www


RUN chown -R nginx:nginx /etc/nginx

CMD /bin/sh -c "envsubst '\$FASTCGI_PASS' < /tmp/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"


EXPOSE 80
