monolog:
    handlers:
        main:
            type:  stream
            path:  "php://stdout" # instead of writing to a file we broadcast
            level: warning
            formatter: log.custom.formatter
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
