
app_api:
    resource: "@AppApiBundle/Controller/"
    type:     annotation
    prefix:   /api

default:
    pattern: /
    defaults: { _controller: AppApiBundle:Version_1_1_0\Default:default }

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc
    
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
