security:
    encoders:
        GemeenteAmsterdam\MakkelijkeMarkt\AppApiBundle\Entity\Account:
            algorithm: bcrypt
    role_hierarchy:
        ROLE_SERVICE: ~
        ROLE_USER: ~
        ROLE_ADMIN: [ROLE_USER, ROLE_SENIOR]
        ROLE_SENIOR: [ROLE_USER]
    providers:
        in_memory:
            memory: ~
        api_key_user_provider:
            id: api_key_user_provider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern: ^/api
            stateless: true
            anonymous: ~
            simple_preauth:
                authenticator: apikey_authenticator
            provider: api_key_user_provider
        main:
            anonymous: ~
            