name: deploy-mm-api

trigger: none

parameters:
  - name: preSteps
    type: object
    default:
      - script: kubectl get all
        displayName: kubectl get all
      - script: kubectl get all
        displayName: kubectl get all

variables:
  # Debugging
  System.Debug: true

resources:
  repositories:
    - repository: azure-templates
      type: git
      name: salmagundi/azure-templates
      ref: refs/heads/tamm-late

extends:
  template: pipelines/aks/template.yaml@azure-templates
  parameters:
    name: deploy-mm-api
    build:
      pool:
        name: ContainerBuilder
    dev:
      pool: salmagundi
      namespace: ns-ccc-mrkt-ont-01-markten
      kubernetesServiceConnection: SCN-K8S-ns-ccc-mrkt-ont-01-markten
      presteps: ${{ parameters.preSteps }}

    # test:
    #   pool: salmagundi
    #   namespace: ns-ccc-salm-tst-01-mm-api
    #   kubernetesServiceConnection: SCN-K8S-ns-ccc-salm-tst-01-mm-api