
services:
  import.process.perfectviewmarktimport:
    class: GemeenteAmsterdam\MakkelijkeMarkt\ImportBundle\Process\PerfectViewMarktImport
    arguments:
      - '@appapi.repository.markt'
      - '@appapi.repository.marktextradata'
      - '@doctrine.orm.entity_manager'
  import.process.perfectviewkoopmanimport:
    class: GemeenteAmsterdam\MakkelijkeMarkt\ImportBundle\Process\PerfectViewKoopmanImport
    arguments:
      - '@doctrine.dbal.default_connection'
  import.process.perfectviewvervangerimport:
    class: GemeenteAmsterdam\MakkelijkeMarkt\ImportBundle\Process\PerfectViewVervangerImport
    arguments:
      - '@doctrine.dbal.default_connection'
  import.process.perfectviewsolliciatieimport:
    class: GemeenteAmsterdam\MakkelijkeMarkt\ImportBundle\Process\PerfectViewSollicitatieImport
    arguments:
      - '@doctrine.dbal.default_connection'
  import.process.perfectviewfotoimport:
    class: GemeenteAmsterdam\MakkelijkeMarkt\ImportBundle\Process\PerfectViewKoopmanFotoImport
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%kernel.data_dir%'

      